### ISSUE TITLE
Bug on function call of F.grid_sample()? 

### ISSUE THREAD

**Issue by jeasinema** [Gasoonjia/tvnet_pytorch#1]
Related code [here](https://github.com/Gasoonjia/tvnet_pytorch/blob/master/model/losses/flow_loss.py#L43)

It seems that if we change to use `F.grid_sample()` from `spatial_transform()`, the third param that specifies the output shape should be removed. Since `F.grid_sample()` does not accept this param at all.

**Comment by Gasoonjia** [comment]
Thank you! The bug has been fixed!
